app = "flask-versioned-store"
primary_region = "ams"

[env]
  FLASK_ENV = "production"
  PORT = "8080"
  STORAGE_BASE_DIR = "/data/store"

[mounts]
  source = "data"
  destination = "/data/store"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 8080
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
